services:
  postgres-fraud:
    container_name: stockmarketpostgresfraud2
    image: postgres
    environment:
      POSTGRES_USER: stockmarket
      POSTGRES_PASSWORD: stockmarket
      PGDATA: /data/postgresfraud2
    volumes:
      - postgres:/data/postgresfra
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-notification:
    container_name: stockmarketpostgresnotification
    image: postgres
    environment:
      POSTGRES_USER: stockmarket
      POSTGRES_PASSWORD: stockmarket
      PGDATA: /data/notifi
    volumes:
      - postgres:/data/notifi
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: stockmarketpostgrescustomer2
    image: postgres
    environment:
      POSTGRES_USER: stockmarket
      POSTGRES_PASSWORD: stockmarket
      PGDATA: /data/postgrescustomer
    volumes:
      - postgres:/data/postgrescust
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"



networks:
  postgres:
    driver: bridge
  postgres-fraud:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  postgres-fraud:
  notification: