server:
  port: 8086
spring:
  application:
    name: notification
  datasource:
    password: stockmarket
    url: jdbc:postgresql://localhost:5435/notification
    username: stockmarket
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  profiles:
    active: native


rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key